Implement partial Package by feature folder organization.
bowe-td/react-web-example pull request #12
Opened 2020-09-16 23:40 UTC by BrunoBNascimento

2020-09-16 23:44 UTC, gustavoarsantos commented
Resolva os conflitos.. 👯

2020-09-16 23:48 UTC, gustavoarsantos approved these changes

2020-09-16 23:58 UTC, heitortv approved these changes

2020-09-17 00:03 UTC, heitortv commented
feature/f-by-package

2020-09-17 00:04 UTC, heitortv commented
![2020-09-16-210230_682x343_scrot](https://user-images.githubusercontent.com/26033412/93404267-1e78bf00-f860-11ea-93a2-22b002cf2e60.png)

Linter warnings are happening

2020-09-17 00:29 UTC, Goufix requested changes

2020-09-17 00:29 UTC, Goufix commented on src/modules/Auth/ForgotPassword.tsx
> +Login.propTypes = {};
Prop types

2020-09-17 00:29 UTC, Goufix commented on src/modules/Auth/SignUp.tsx
> +const Login = () => {
SignUp

2020-09-17 00:29 UTC, Goufix commented on src/modules/Auth/SignUp.tsx
> +export default Login;
Signup

2020-09-17 00:29 UTC, Goufix commented on src/modules/index.tsx
> +import Home from './Auth';
Home from './auth' ?

2020-09-17 01:13 UTC, Goufix approved these changes

2020-09-17 03:55 UTC, merged